name: Continuous Integration

on: [push, workflow-dispatch]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Cache Yarn Deps
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - name: Cache Pods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-
      - name: Update Pods
        working-directory: ./ios
        run: |
          gem update cocoapods xcodeproj
          pod install
      - name: Run iOS
        run: |
          yarn run ios
      - name: Run test
        run: |
          yarn test