name: Continuous Integration

on: push

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install node modules
      run: |
        yarn install
    - name: Run iOS
      run: |
        yarn run ios
    - name: Run test
      run: |
        yarn test